### ISSUE TITLE
Hover over menus don't work on touch/mobile devices

### ISSUE THREAD

**Issue by oshotton** [SWAuk/com_swa#122]
Hover over menus don't work on touch/mobile devices. Make onclick work the same as hover over?

**Comment by CJxD** [comment]
My branch on TPL_SWA resolves this

**Comment by oshotton** [comment]
Argh, good to know!

**Comment by Beaker69** [comment]
You have to consider how long we will be using archaic touch screens though... I just let Siri run my life now... "Siri! Book me an Xswa ticket to Aussie kiss and find me a naive fresher!"
:)
Sent from my iPhone

On 9 Oct 2015, at 20:49, oshotton <notifications@github.com> wrote:

Argh, good to know!

**Comment by oshotton** [comment]
Hahahaa lmfao! Yess beaker!

**Comment by Beaker69** [comment]
I'm on my way to the Xswa annual reunion now but have got a few days off work this week and my laptop with me in Cornwall so if you guys want me to have a cruise round the site finding bugs I'm more than happy to. I trained myself to think like a dummass fresher from a northern poly over years in order to perfect the ability to properly test my code!

Sent from my iPhone

On 9 Oct 2015, at 22:00, oshotton <notifications@github.com> wrote:

Hahahaa lmfao! Yess beaker!

**Comment by oshotton** [comment]
Haha! I've just arrived here at XSWA also got laptop, help is always
welcome! :)

**Comment by addshore** [comment]
@CJxD epic!
I'll get this on the site soon! :)

**Comment by addshore** [comment]
Looks fixed with the new template
