### ISSUE TITLE
Duplicate Universities

### ISSUE THREAD

**Issue by oshotton** [SWAuk/com_swa#126]
Noticed a Manchester2 and Falmouth2 exist without any members.

Query used to see no members:

SELECT user.name
FROM `swan_users` AS user
JOIN `swan_swa_member`AS member ON user.id = member.user_id
JOIN `swan_swa_university_member` AS uni_member ON member.id = uni_member.member_id
WHERE uni_member.university_id = 86 OR uni_member.university_id = 85

**Comment by addshore** [comment]
Before removing just need to check they are not used anywhere else ;)

**Comment by addshore** [comment]
85 -> 65
86 -> 70

UPDATE swan_swa_member SET university_id = 65 WHERE university_id = 85;
UPDATE swan_swa_university_member SET university_id = 65 WHERE university_id = 85;
UPDATE swan_swa_deposit SET university_id = 65 WHERE university_id = 85;
UPDATE swan_swa_event_host SET university_id = 65 WHERE university_id = 85;
UPDATE swan_swa_team_result SET university_id = 65 WHERE university_id = 85;
UPDATE swan_swa_damages SET university_id = 65 WHERE university_id = 85;

UPDATE swan_swa_member SET university_id = 70 WHERE university_id = 86;
UPDATE swan_swa_university_member SET university_id = 70 WHERE university_id = 86;
UPDATE swan_swa_deposit SET university_id = 70 WHERE university_id = 86;
UPDATE swan_swa_event_host SET university_id = 70 WHERE university_id = 86;
UPDATE swan_swa_team_result SET university_id = 70 WHERE university_id = 86;
UPDATE swan_swa_damages SET university_id = 70 WHERE university_id = 86;

DELETE FROM swan_swa_university WHERE id = 85;
DELETE FROM swan_swa_university WHERE id = 86;

Turns out these were not used anywhere, no rows were changed but the 2 unis are now gone!
